export const REPO_TEST_REQUEST = 'REPO_TEST_REQUEST';
export const REPO_TEST_SUCCESS = 'REPO_TEST_SUCCESS';
export const REPO_TEST_FAILURE = 'REPO_TEST_FAILURE';

export const REPO_DETAIL_TEST_REQUEST = 'REPO_DETAIL_TEST_REQUEST';
export const REPO_DETAIL_TEST_SUCCESS = 'REPO_DETAIL_TEST_SUCCESS';
export const REPO_DETAIL_FAILURE = 'REPO_DETAIL_FAILURE';
